name: Java Continuous Integration

on:
  pull_request:
    branches:
      - master

jobs:
  test_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java
        with:
          java-version: 21

      - name: Build with Maven
        run: mvn clean install

      - name: Run Tests
        run: mvn test


