name: Java Continuous Integration

on:
  pull_request:
    branches: [ main ]

jobs:
  test_pull_request:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java
        with:
          java-version: 21
      - run: mvn clean install
      - run: mvn test
